train_csv_path = '../datasets/data/train.csv'
test_csv_path = '../datasets/data/test.csv'
sample_train_csv_path ='../datasets/data/train_sample.csv'
sample_test_csv_path = '../datasets/data/test_sample.csv'
processed_train_csv_path = '../datasets/data/processed_train.csv'
processed_test_csv_path = '../datasets/data/processed_test.csv'